Port from Moo to Mite
robrwo/Linux-Statm-Tiny pull request #13
Opened 2022-06-29 14:04 UTC by tobyink

Here's a pull request to make `Linux::Statm::Tiny` truly tiny, eliminating all non-core dependencies. It uses Mite, a tool which Michael Schwern wrote a while back and I've been trying to make more useful.

The idea of Mite is that it creates a small shim module (`Linux::Statm::Tiny::Mite`) to handle your OO needs. When you upload your distribution to CPAN, you include that shim module, and your distribution doesn't need to depend on Mite at all. Mite is only used in the development process.

Up to you whether you accept this pull request or not. Your module just seemed like a really good candidate for porting. The one thing that was a little unpleasant was having to replace `MooX::Aliases`, and I think aliases are possibly something that should be added to Mite.

2022-06-29 14:08 UTC, robrwo commented
I'm fine with it. @JRaspass (RAZ) is the main maintainer now.

2022-06-29 14:27 UTC, JRaspass commented
Ooo this looks fun, I had started a pure perl (bless, etc) port of this dist some time ago, I had been meaning to get back to it, but using Mite is very interesting.

So my vague understanding of Mite is that we write OOP and transpile down to pure perl and commit that next to the original?

I'll give this PR a proper look this weekend, but in general I like it!

2022-06-29 14:32 UTC, JRaspass commented
This was my WIP code for that rewrite https://github.com/JRaspass/Linux-Statm-Tiny/commit/555f8956e3d6e0837c9a53520892b38df0dbaaef

Very rough around the edges, and changed the API slightly but I really liked how much easier the suffixed aliases were to read:
```perl
while ( my ( $method, $stat ) = each %methods ) {
    while ( my ( $suffix, $factor ) = each %suffixes ) {
        no strict 'refs';

        *{ $method . $suffix } = sub { POSIX::ceil shift->{$stat} * $factor };
    }
}
```

Incidentally that use of `POSIX::ceil` is why I ended up contributing `builtin::ceil` to 5.36. If/once builtin becomes dual life it would be the perfect dep for this dist, I think dual life dists are fair game for a ::Tiny dist. Especially when POSIX is so damn heavy.

2022-06-29 15:08 UTC, tobyink commented
> So my vague understanding of Mite is that we write OOP and transpile down to pure perl and commit that next to the original?

Yes. Basically you end up with:

* `lib/Linux/Statm/Tiny.pm`
* `lib/Linux/Statm/Tiny.pm.mite.pm`

The former includes `use Linux::Statm::Tiny::Mite`. During normal usage, `Linux::Statm::Tiny::Mite` autoloads `*.mite.pm` files for you. During the compilation stage, it *generates* the `*.mite.pm` files.

2022-06-30 10:01 UTC, JRaspass requested changes

2022-06-30 10:01 UTC, JRaspass commented on lib/Linux/Statm/Tiny.pm
> +            $aliases{$attr} ? (alias => $aliases{$attr}."_${alt}") : (),
Seems like an unnecessary change?

2022-06-30 10:01 UTC, JRaspass commented on lib/Linux/Statm/Tiny.pm
> -
These blank line removals seem like style, I would expect just Moo* to be replaced by `Linux::Statm::Tiny::Mite`.

2022-06-30 10:01 UTC, JRaspass commented on lib/Linux/Statm/Tiny.pm
> +        @aliases ? (alias => \@aliases) : (),
Does Mite not cope with an empty array of aliases? The original approach seems simpler imo.

2022-06-30 12:54 UTC, tobyink commented on lib/Linux/Statm/Tiny.pm
> +            $aliases{$attr} ? (alias => $aliases{$attr}."_${alt}") : (),
Yeah, it's just because the line was removed entirely as Mite didn't support aliases. Then I added support for aliases to Mite so added it back in again by hand, and the whitespace didn't quite match.

2022-06-30 13:02 UTC, tobyink commented on lib/Linux/Statm/Tiny.pm
> +        @aliases ? (alias => \@aliases) : (),
It doesn't. I should fix that.

2022-06-30 13:09 UTC, tobyink commented on lib/Linux/Statm/Tiny.pm
> +        @aliases ? (alias => \@aliases) : (),
This should fix the error.
https://metacpan.org/release/TOBYINK/Mite-0.001012

2022-07-01 19:15 UTC, merged

2022-07-26 15:58 UTC, robrwo commented
@JRaspass are you going to release this?

2022-07-26 16:19 UTC, robrwo commented
I'll release this.

2022-07-26 17:08 UTC, JRaspass commented
Thanks @robrwo, I've been swamped of late. I was looking into your dist.ini and seeing how to do TRIAL releases but I suspect it doesn't really need one.

2022-07-26 17:10 UTC, robrwo commented
There was also a problem with the `dist.ini` prereqs cleaning plugin. I removed it since it's better to include core prereqs anyhow.